### ISSUE TITLE
Support for animation

### ISSUE THREAD

**Issue by lancevalour** [gamecreature/QtAwesome#12]
Is there any way to make spinner spin? Font Awesome has the option to make icon animated. Thanks.

**Comment by gamecreature** [comment]
I really would like to support this. Problem is that as far as I know, updating a QIcon is simply by replacing it with another icon... So the animation support should happen on the control and not on the icon.

So I don't know how exactly how to fit it in this library :S

See this example:  http://stackoverflow.com/questions/15374191/how-to-set-animated-icon-to-qpushbutton-in-qt5

**Comment by SylvainCorlay** [comment]
@gamecreature we have some support for animation in the python port. You
might be interested to check it out.
S.

I really would like to support this. Problem is that as far as I know,
updating a QIcon is simply by replacing it with another icon... So the
animation support should happen on the control and not on the icon.

So I don't know how exactly how to fit it in this library :S

See this example:
http://stackoverflow.com/questions/15374191/how-to-set-animated-icon-to-qpushbutton-in-qt5

—
Reply to this email directly or view it on GitHub
<https://github.com/gamecreature/QtAwesome/issues/12#issuecomment-157812278>
.

**Comment by gamecreature** [comment]
Thanks @SylvainCorlay
Nice solution.. I will check it out when I've got some time. 
Need to see how to fit this nicely in c++ ...  Python is very dynamic language ;)

**Comment by gamecreature** [comment]
I've implemented the basics for animation. Unfortunately I Accidentally committed it to the master and pushed it :S. I've meant to implement this in a separate branch, to work out the interface..
The animation now works.. I still need to fix the following issues:
- Memory management to cleanup animation objects when destroying the icon/widget
- nicer interface the adding it to a qvariant map
- make 2 examples, one with animation and one without

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by lancevalour** [comment]
Awesome！

2015年12月8日星期二，Sylvain Corlay <notifications@github.com> 写道：
