### ISSUE TITLE
not rendering properly

### ISSUE THREAD

**Issue by stefanchiriac** [gamecreature/QtAwesome#19]
Hello,

I'm using qt 4.8.6 with ubuntu 16.04 and I'm trying to insert an icon inside a button, but the result is not rendering properly.

```
            QPushButton *deleteButton = new QPushButton();
            deleteButton->setFlat(true);
            deleteButton->setFixedWidth(32);
            deleteButton->setFixedHeight(32);
            deleteButton->setIcon(awesome->icon(fa::remove));
            deleteButton->setIconSize(QSize(32, 32));
            deviceLayout->addWidget(deleteButton);
```

![qtfa](https://cloud.githubusercontent.com/assets/5517703/15338713/c951f50c-1c89-11e6-8fbd-b2369f92e8e6.png)

Any idea what could be wrong, or am I missing something?
Thanks

**Comment by gamecreature** [comment]
Hmmm very strange. I don't have a Linux environment to test it.
Wat happens if you remove all the size options: (setFixedWidth, setIconSize.. etc??)

else please try the following workaround: 
```
deleteButton->setIcon(awesome->icon(fa::beer).pixmap(32,32));
```

**Comment by stefanchiriac** [comment]
I removed everything and tried the workaround and still the same.
If I put fa::beer that's how it looks like now
![screenshot from 2016-05-18 23-29-25](https://cloud.githubusercontent.com/assets/5517703/15373907/6e9012c6-1d50-11e6-9eca-e3e2aebbb152.png)

**Comment by gamecreature** [comment]
It just looks like as if the wrong font is used...?
Did the loading of the TTF font succeed?

Are other controls working?

**Comment by stefanchiriac** [comment]
solved. Was initialized in the first window and on the 2nd window was not sharing the same instance

**Comment by gamecreature** [comment]
Thanks for posting the cause and closing this issue!! 👍🏻
