### ISSUE TITLE
error: ‘qt_metatype_id’ is not a member of ‘QMetaTypeId<QtAwesomeAnimation*>’

### ISSUE THREAD

**Issue by kuvark** [gamecreature/QtAwesome#23]
Hi,

I tried to compile your sample code and I got this error. Any idea?

/usr/include/qt4/QtCore/qmetatype.h:169:79: error: ‘qt_metatype_id’ is not a member of ‘QMetaTypeId<QtAwesomeAnimation*>’ static inline int qt_metatype_id() { return QMetaTypeId<T>::qt_metatype_id(); }

**Comment by gamecreature** [comment]
Is see qt4 in your include path...
I don't know if it still compiles with Qt 4?

**Comment by gamecreature** [comment]
@kuvark, Could you please confirm this new commit fixes your problem?
