### ISSUE TITLE
Problem with icon 4.7

### ISSUE THREAD

**Issue by olivierduguay** [gamecreature/QtAwesome#24]
Not quite sure why, but I can't use the new (4.7) icons... 
I updated & recompile the files, but when I use one of the new icons, the icon is just a small rectangle...

Thanks in advance for your help!
Olivier

**Comment by gamecreature** [comment]
Could you supply me with some more information?
Code-Sample, environment information etc..

**Comment by olivierduguay** [comment]
My bad, just found out that I included the bad header file :P (QtAwesome.h) ... That did not make crash the app. but surely could find the icon in the fa::icon enum ! 

Thanks for your time ahahah

**Comment by olivierduguay** [comment]
Thanks again for this awesome code !

**Comment by gamecreature** [comment]
Great to hear your problem is solved 😄
