### ISSUE TITLE
On windows 10, the an icon in QPushButton that is selected isn't shown

### ISSUE THREAD

**Issue by SverrirValgeirsson** [gamecreature/QtAwesome#30]
Hi there. 
In latest versions of QtAwesome it seems that the painting fails somehow for a selected QPushButton. 
If I make sure that the paint method sets modePostfix = "" and optionKeysForModeAndState() does the same, I at least get the paintings working as previously. 
I haven't dug more into it since just skipping the two switch statements solved my issue for now.

**Comment by SverrirValgeirsson** [comment]
Hi. The code is here. Should compile out of the box.
https://github.com/SverrirValgeirsson/Todo

This happens for all the buttons I have it seems. Both with "checkable" option and no options.

**Comment by gamecreature** [comment]
Running on OS X, this issue isn't happening. 
Though I've merged a commit. (merged a fix from https://github.com/gamecreature/QtAwesome/issues/29)
Could you please check if this solves your issue?

**Comment by SverrirValgeirsson** [comment]
I didn't get it on OSX either. But both Linux and Windows had the same problem. 
With this change you did now it is fixed.

Thanks :)
