### ISSUE TITLE
Do you plan to update to the latest version?

### ISSUE THREAD

**Issue by DaeHeeLim** [gamecreature/QtAwesome#32]
First, thanks for the great software.

Do you plan to update to the latest version? ( Font awesome 5.x )

**Comment by gamecreature** [comment]
That's  a good one.  It's been on mind..  
Yes I think we need to update to the latest version. (Maybe create a new project for it)

Problems is that there is a commercial and an non-commercial version.
I think there should a non-commercial non-pro version version. (Maybe add support for the pro icons, but you are required to copy the font-files to the project yourself)
Another difference with the current version is the inclusion of style (solid, regelar, light and brands)

**Comment by aldumas** [comment]
If I want to use the most recent free version, is it as simple as doing the following?

- Replace the file in QtAwesome/fonts with your desired font. 
- QtAwesome.h
  - Update enum icon.
- QtAwesome.cpp
  - Update faNameIconArray.
  - Update ttf filename in the resource string in QtAwesome::initFontAwesome().
- QtAwesome.qrc
  - Update ttf filename.

**Comment by gamecreature** [comment]
@aldumas That is a possibility, though It would be nice if there was support for using commercial fonts.

Also it's a bit more complex, because the fonts a in different fonts categories: solid, regular, light and brands

**Comment by dibok** [comment]
Any progress here? I have 4.7.0 version and missing volume-muted icon. So I tried to download latest FontAwesome version but seems that they don't support .ttf format anymore, only .otf. Changed QtAwesome (re)source to load .otf file but icons looks bad, very bad, much less details, looks like issues with rounding and antyalias. Tried web conversions from otf to ttf but still same looking

**Comment by dibok** [comment]
Mmmm, actually no, seems that they changed a bit all icons in recent version. I was just accustomed to 4.7.0 look in my Qt app but when I compare otf loaded icons to fontawesome website gallery they looks exactly the same. For example icons "play" or "stop" are now much rounded while in 4.7.0 they have sharp edges. Maybe false alarm but I still think that the smaller icon is, the worse quality is, maybe some kind of issue with scaling otf icons but I'm not sure. Anyone can say that QtAwesome can handle otf format same as ttf?

**Comment by gamecreature** [comment]
Supporting fontawesome 4.7 will break backwards compatibility with this library.
I guess we need to make a new library or seperate branch for this.

**Comment by ahaeberle** [comment]
This would be a great idea. Maybe considering other font-awesome like projects like line-awesome

**Comment by mbsanchez** [comment]
I've updated this code to new version 5.10.2, which support pro and free versions fo the font awesome icons, however you need to include the pro font files if you have the license. Moreover, you can't use the free version without limits. 

I hope @gamecreature accepts my pull request.

**Comment by gamecreature** [comment]
Font Awesome 5 has been released.
The 5 version is on separate branch
