### ISSUE TITLE
macOS darkmode

### ISSUE THREAD

**Issue by ra1nb0w** [gamecreature/QtAwesome#33]
first of all thanks for your work!
I am using another software [openhantek](https://github.com/OpenHantek/openhantek) that use your library. Unfortunately in macOS with darkmode the icons are nearly indistinguishable with the background (see the image at the end). Before patching openhantek I would like to ask you if that change could be fit on this library?
Just for test I did
```c++
iconFont->setDefaultOption( "color", QColor(255,100,100) );
iconFont->setDefaultOption( "color-disabled", QColor(155,60,10));
iconFont->setDefaultOption( "color-active", QColor(100,100,100));
iconFont->setDefaultOption( "color-selected", QColor(12,240,100));

iconFont->setDefaultOption( "color-off", QColor(255,100,100) );
iconFont->setDefaultOption( "color-disabled-off", QColor(155,60,10));
iconFont->setDefaultOption( "color-active-off", QColor(100,100,100));
iconFont->setDefaultOption( "color-selected-off", QColor(12,240,100));
```
and it works.

Default behaviour of QtAwesome in openhantek. The red icon that is visible is an svg file.

![04dfe172-bec4-43c2-93d8-6492a0f4e7b2](https://user-images.githubusercontent.com/1543838/54739831-b63d1480-4bb9-11e9-9b1a-ff2e6db93878.png)

**Comment by gamecreature** [comment]
Good question. I think the default colors for QtAwesome should be retrieved from the system.
```c++
 QApplication::palette()
```
At the moment they are hardcoded!

**Comment by ra1nb0w** [comment]
something like

```c++
    QPalette palette;                  
    setDefaultOption("color", palette.color(QPalette::Dark));   
    setDefaultOption("color-off", palette.color(QPalette::Dark));
    setDefaultOption("color-disabled", palette.color(QPalette::Midlight));
    setDefaultOption("color-active", palette.color(QPalette::Light));
    setDefaultOption("color-selected", palette.color(QPalette::Light));  
```

**Comment by gamecreature** [comment]
The new release should improve the dark/light mode situation. The default options now are based on the palette:

```c++
setDefaultOption("color", QApplication::palette().color(QPalette::Normal, QPalette::Text));
setDefaultOption("color-disabled", QApplication::palette().color(QPalette::Disabled, QPalette::Text));
setDefaultOption("color-active", QApplication::palette().color(QPalette::Active, QPalette::Text));
setDefaultOption("color-selected", QApplication::palette().color(QPalette::Active, QPalette::Text));
```

**Comment by gamecreature** [comment]
I guess this issue can be marked as done (see previous comment)
