### ISSUE TITLE
Incompatibility with the new Qt 5.14

### ISSUE THREAD

**Issue by olivierduguay** [gamecreature/QtAwesome#37]
It think there might be a problem with the compilation/building of the QtAwesome library with the newest version of Qt (version 5.14.0), using MSVC_2015, 64bits.

I used to compile this library using Qt 5.7.1 and Qt 5.13.x (also with MSVC_2015, 64bits) and never run into a single problem. But today, I downloaded the newest Qt version (5.14.0) and with this kit, I always run into this error : 

*** C1001 : An internal error has occured in the compiler.
C:\Qt\5.14.0\msvc2015_64\include\QtCore\qsrtring.h

and this error is linked to those lines of code in the qstring.h file :

```
#ifdef Q_CLANG_QDOC
    QString
#else
    typename std::enable_if<
        sizeof...(Args) >= 2 && std::is_same<
            QtPrivate::BoolList<is_convertible_to_view_or_qstring<Args>::value..., true>,
            QtPrivate::BoolList<true, is_convertible_to_view_or_qstring<Args>::value...>
        >::value,
        QString
    >::type
#endif 
```

The error seems to be really related to QtAwesome since I'm able to build everything else in the project independently (excepted the parts using the QtAwesome library functions)

Hope I made my problem clear for you guys and hopefully someone will comes out with a fix or an idea on how to fix it because I'm pretty much out of idea myself...

**Comment by gamecreature** [comment]
Hi Olivier,

Are you sure this has something to do with QtAwesome?
Dit you perform a full cleanup?
Which branch did you use? The master or the fontawesome-5 branch?

**Comment by demiantres** [comment]
FYI: In my projects QtAwesome works perfectly fine with Qt 5.14 (iOS, Android, macOS, Windows).

**Comment by olivierduguay** [comment]
Thanks for your suggestion ! I found out that my problem is related with the fact that I'm using the Pro version of FontAwesome... 

I'm currently using the FontAwesome Pro version 5.11.2. When I comment the `#CONFIG += fontAwesomePro` part and uncomment the `CONFIG += fontAwesomeFree` part, everything works as expected (except for the "pro" logo I can't used anymore)

The only thing that change is the resource file included (.qrc) and the files it include (the .otf files coming from FontAwesome)... My guess is now that the version 5.11.2 of the icons is not compatible with Qt 5.14...

**Comment by gamecreature** [comment]
I closing this issue, if it's still problem please let me know
