### ISSUE TITLE
Take existing QPixmap/QImage/QIcon as source?

### ISSUE THREAD

**Issue by Dariusz1989** [gamecreature/QtAwesome#54]
Hey

Its an awesome engine that can colorize icons based on state/etc. It would be great if it could take any of the other 3 types of pixmaps and draw that + its states/etc logic.

Regards
Dariusz

**Comment by gamecreature** [comment]
Thanks for the suggestion. This looks like nice addition!

**Comment by Dariusz1989** [comment]
Hey
Hmm I can't quite remember the details now (sigh) but I was trying to control QToolButton checked state/etc via icon. The default one did not quite work and I remember wacking up something custom. I'll dig in to code see if I can get example to show why this would help here.
