### ISSUE TITLE
Backwards compatability with Qt5? 

### ISSUE THREAD

**Issue by zethon** [gamecreature/QtAwesome#57]
Has anyone tried this with Qt5 lately? Does it still work?

**Comment by gamecreature** [comment]
@zethon I just confirmed the latest Qt5 and latest QtAwesome builds and runs the sample project on my Intel Mac. I will close this issue.

**Comment by zethon** [comment]
Yup, I should have responded, but I tried it in Qt5 and it works like a charm. Thanks!
